flowchart TB
  subgraph n_lane_01_customer["customer"]
    n_J_020("Submit Claim")
    n_J_021("Receive Confirmation")
  end
  subgraph n_lane_02_frontstage["frontstage"]
    n_PR_020["Validate Claim"]
  end
  subgraph n_lane_03_backstage["backstage"]
    n_PR_021["Review Claim History"]
  end
  subgraph n_lane_04_support["support"]
    n_PR_022["Notify Customer"]
  end
  subgraph n_lane_05_system["system"]
    n_SA_020[["Store Claim"]]
    n_SA_021[["Load Claim History"]]
    n_SA_022[["Send Email"]]
    n_D_020["Claim"]
  end
  subgraph n_lane_06_policy["policy"]
    n_PL_020["Retention Policy"]
  end
  n_J_020 --> n_J_021
  n_J_020 --> n_PR_020
  n_J_021 --> n_PR_022
  n_PR_020 --> n_PL_020
  n_PR_020 --> n_SA_020
  n_PR_020 --> n_PR_021
  n_PR_021 --> n_SA_021
  n_PR_021 --> n_PR_022
  n_PR_022 --> n_SA_022
  n_SA_020 --> n_PL_020
  n_SA_020 --> n_D_020
  n_SA_020 --> n_D_020
  n_SA_021 --> n_D_020
  n_SA_022 --> n_D_020
  linkStyle 1,2,10,12,13 stroke-dasharray: 6 4;
  linkStyle 3,9 stroke-dasharray: 2 4;
  linkStyle 11 stroke-width: 3px;
