flowchart TB
  subgraph n_step["Steps"]
    n_J_010("Select a Node")
    n_J_020("Review Diagrams Containing Current Node")
    n_J_040("Add Relationship")
    n_J_041("Add relationship, by node")
    n_J_042("Add outgoing relationship")
    n_J_043("Add incoming relationship")
    n_J_021("Select Diagram")
    n_J_022("View Node in New Diagram Context")
    n_J_030("Select Diagram Content")
    n_J_031("Adjust View")
    n_J_032("Name the New View")
  end
  n_J_010 --> n_J_020
  n_J_010 --> n_J_040
  n_J_020 --> n_J_021
  n_J_021 --> n_J_022
  n_J_030 --> n_J_031
  n_J_031 --> n_J_032
  n_J_040 --> n_J_041
  n_J_040 --> n_J_042
  n_J_040 --> n_J_043
