flowchart TB
  subgraph n_step["Steps"]
    n_S_001("Select item<br/>Refines: Submit order (BP-002)<br/>Refines: Choose purchase (J-001)")
    n_S_002("Review order<br/>Refines: Prepare order (BP-001)<br/>Refines: Choose purchase (J-001)")
    n_S_003("Submit purchase<br/>Refines: Prepare order (BP-001)<br/>Refines: Confirm purchase (J-002)")
  end
  subgraph n_place["Places"]
    n_P_001("Checkout")
    n_P_002("Confirmation")
  end
  subgraph n_view_state["View States"]
    n_VS_001("Order review")
  end
  n_S_001 --> n_S_002
  n_S_001 --> n_P_001
  n_S_002 --> n_S_003
  n_S_002 --> n_VS_001
  n_S_003 --> n_P_002
  classDef dashedNode stroke-dasharray: 6 4;
  class n_VS_001 dashedNode;
  linkStyle 1,3,4 stroke-dasharray: 2 4;
