flowchart LR
  subgraph n_P_100[" "]
    n_P_100__anchor["Dashboard<br/>/dashboard<br/>[auth]"]
    n_C_900("Global Navigation")
  end
  subgraph n_P_110[" "]
    n_P_110__anchor["Report View<br/>/dashboard/report-view<br/>[auth]"]
  end
  subgraph n_P_210[" "]
    n_P_210__anchor["Projections Overview<br/>/projections<br/>[auth]"]
    n_VS_210a("Projection List<br/>data: ProjectionCollection")
    n_VS_210b("Duplicate Projection Dialog<br/>data: SelectedProjection")
    n_VS_210c("Delete Projection Confirmation Dialog<br/>data: SelectedProjection")
    n_VS_210d("Add Projection to Dashboard Confirmation Dialog<br/>data: SelectedProjection")
    n_C_900("Global Navigation")
  end
  subgraph n_P_220[" "]
    n_P_220__anchor["Projection<br/>/projections/projection<br/>[auth]"]
    n_VS_220a("Overview Tab<br/>data: ProjectionOverview")
    n_VS_220b("Fee Schedules Tab<br/>data: FeeScheduleScenario")
    n_VS_220c("Funds Tab<br/>data: FundingScenario")
  end
  subgraph n_P_221[" "]
    n_P_221__anchor["Fee Schedule Scenario Details<br/>/projections/projection/fee-schedule-scenario-details<br/>[auth]"]
  end
  subgraph n_P_222[" "]
    n_P_222__anchor["Funding Scenario Details<br/>/projections/projection/funding-scenario-details<br/>[auth]"]
  end
  subgraph n_P_230[" "]
    n_P_230__anchor["Create New Projection<br/>/projections/create-new-projection<br/>[auth]"]
    n_VS_230a("Create New Projection Step 1<br/>data: ProjectionBasics")
    n_VS_230b("Create New Projection Step 2<br/>data: FeeScheduleSelection")
    n_VS_230c("Create New Projection Step 3<br/>data: FundingScenarioSelection")
  end
  subgraph n_P_310[" "]
    n_P_310__anchor["Current Bills<br/>/current-bills<br/>[auth]"]
    n_C_900("Global Navigation")
  end
  subgraph n_P_410[" "]
    n_P_410__anchor["Review Past Bills<br/>/review<br/>[auth]"]
    n_C_900("Global Navigation")
  end
  subgraph n_P_510[" "]
    n_P_510__anchor["Manage Accounts<br/>/accounts<br/>[auth]"]
    n_C_900("Global Navigation")
  end
  subgraph n_P_610[" "]
    n_P_610__anchor["Manage Fee Schedules<br/>/fee-schedules<br/>[auth]"]
    n_C_900("Global Navigation")
  end
  n_VS_230a --> n_VS_230b
  n_VS_230b --> n_VS_230c
  classDef dashedNode stroke-dasharray: 6 4;
  class n_VS_210a,n_VS_210b,n_VS_210c,n_VS_210d,n_VS_220a,n_VS_220b,n_VS_220c,n_VS_230a,n_VS_230b,n_VS_230c dashedNode;
  classDef containerTitle fill:transparent,stroke:transparent,color:#111;
  class n_P_100__anchor,n_P_110__anchor,n_P_210__anchor,n_P_220__anchor,n_P_221__anchor,n_P_222__anchor,n_P_230__anchor,n_P_310__anchor,n_P_410__anchor,n_P_510__anchor,n_P_610__anchor containerTitle;