flowchart TB
  subgraph n_place["Places"]
    n_P_100("Dashboard")
    n_P_110("Report View")
    n_P_210("Projections Overview")
    n_P_220("Projection")
    n_P_221("Fee Schedule Scenario Details")
    n_P_222("Funding Scenario Details")
    n_P_230("Create New Projection")
    n_P_310("Current Bills")
    n_P_410("Review Past Bills")
    n_P_510("Manage Accounts")
    n_P_610("Manage Fee Schedules")
  end
  subgraph n_view_state["View States"]
    n_VS_210a("Projection List")
    n_VS_210b("Duplicate Projection Dialog")
    n_VS_210c("Delete Projection Confirmation Dialog")
    n_VS_210d("Add Projection to Dashboard Confirmation Dialog")
    n_VS_220a("Overview Tab")
    n_VS_220b("Fee Schedules Tab")
    n_VS_220c("Funds Tab")
    n_VS_230a("Create New Projection Step 1")
    n_VS_230b("Create New Projection Step 2")
    n_VS_230c("Create New Projection Step 3")
  end
  n_P_100 --> n_P_110
  n_P_210 --> n_P_220
  n_P_210 --> n_P_230
  n_P_220 --> n_P_221
  n_P_220 --> n_P_222
  n_P_221 --> n_P_220
  n_P_222 --> n_P_220
  n_P_230 --> n_P_220
  n_VS_230a --> n_VS_230b
  n_VS_230b --> n_VS_230c
  classDef dashedNode stroke-dasharray: 6 4;
  class n_VS_210a,n_VS_210b,n_VS_210c,n_VS_210d,n_VS_220a,n_VS_220b,n_VS_220c,n_VS_230a,n_VS_230b,n_VS_230c dashedNode;
  linkStyle 8,9 stroke-dasharray: 6 4;