flowchart LR
  n_P_100["Dashboard<br/>primary_nav: true"]
  n_P_110["Report View"]
  subgraph n_A_200["Projections"]
    n_P_210["Projections Overview<br/>primary_nav: true"]
    n_P_220["Projection"]
    n_P_221["Fee Schedule Scenario Details"]
    n_P_222["Funding Scenario Details"]
    n_P_230["Create New Projection"]
  end
  subgraph n_A_300["Current Bills"]
    n_P_310["Current Bills<br/>primary_nav: true"]
  end
  subgraph n_A_400["Review"]
    n_P_410["Review Past Bills<br/>primary_nav: true"]
  end
  subgraph n_A_500["Accounts"]
    n_P_510["Manage Accounts<br/>primary_nav: true"]
  end
  subgraph n_A_600["Fee Schedules"]
    n_P_610["Manage Fee Schedules<br/>primary_nav: true"]
  end
  n_P_100 --> n_P_110
  n_P_210 --> n_P_220
  n_P_210 --> n_P_230
  n_P_220 --> n_P_221
  n_P_220 --> n_P_222
  n_P_221 --> n_P_220
  n_P_222 --> n_P_220
  n_P_230 --> n_P_220